- name: "加载"
  type: load
  module: python
  params:
    source: iris.py:load
- name: "X/y 拆分"
  type: X_y
  module: x_y
  params:
    targets: target
- name: "数据集划分"
  type: cross_validate
  module: repeated_stratified_k_fold
  params:
    n_splits: 2
    n_repeats: 2
- name: "模型训练与评估"
  branches:
    - name: "XGBoost"
      type: model
      module: XGB
      params:
        n_estimators: 30
        n_trials: 2
    - name: "LightGBM"
      type: model
      module: LGBM
      params:
        n_estimators: 30
        n_trials: 2
    - name: "CatBoost"
      type: model
      module: CAT
      params:
        iterations: 30
        n_trials: 2
    - name: "RandomForest"
      type: model
      module: RF
      params:
        n_estimators: 30
        n_trials: 2
    - name: "标准化"
      type: x_transformer
      module: standard_scaler
      params:
        numerical_cols: []
      steps:
        - name: "MLP"
          type: model
          module: MLP
          params:
            n_trials: 2
            epochs: 10
            batch_size: 16
            hidden_dims: [16, 8, 4]
